# Generated by Django 5.2 on 2025-08-11 07:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility_owner", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timeslot",
            options={"ordering": ["start_time"]},
        ),
        migrations.RenameField(
            model_name="venue",
            old_name="photos",
            new_name="photo",
        ),
        migrations.RemoveField(
            model_name="court",
            name="operating_hours",
        ),
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="court",
            name="operating_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="court",
            name="operating_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="venue",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="court",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="facility_owner.court",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="facility_owner.timeslot",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"role": "USER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="court",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="court",
            name="price_per_hour",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="court",
            name="sport_type",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="venue",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="venue",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="venue",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="venue",
            name="owner",
            field=models.ForeignKey(
                limit_choices_to={"role": "OWNER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="sport_types",
            field=models.CharField(
                help_text="Comma separated values like 'Badminton,Tennis'",
                max_length=200,
            ),
        ),
    ]
